[package]
name = "wonder-core"
version = "0.1.0"
authors = ["Timothée Haudebourg <wonder@haudebourg.net>"]
edition = "2018"

[dependencies]
vulkano = "*"
engine = { path = "../../engine" }
integer-sqrt = "0.1.3"
