[package]
name = "wonder"
version = "0.1.0"
authors = ["Timothée Haudebourg <wonder@haudebourg.net>"]
edition = "2018"

[dependencies]
integer-sqrt = "0.1.3"
glam = "^0.12"
geometer = { path = "../../utils/geometer" }
scene = { path = "../../utils/scene" }